name: Flutter
on:
  push:

jobs:
  apk:
    name: Build Android APKs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - run: flutter build apk --split-per-abi

      - uses: actions/upload-artifact@v3
        with:
          name: armeabi-v7a.apk
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: arm64-v8a.apk
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk
      - uses: actions/upload-artifact@v3
        with:
          name: x86_64.apk
          path: build/app/outputs/apk/release/app-x86_64-release.apk

  web:
    name: Deploy Web
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - run: flutter build web

      - name: Deploy via Vercel
        id: vercel
        env:
          PROJECT_JSON: ${{ secrets.VERCEL_PROJECT_JSON }}
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          set -e

          cd ./build/web
          { \
            echo '{'; \
            echo '  "version": 2,'; \
            echo '  "builds": ['; \
            echo '  	{ "src": "./**/*", "use": "@now/static" }'; \
            echo '  ]'; \
            echo '}'; \
          } > ./now.json

          mkdir -p ./.vercel && echo "$PROJECT_JSON" > ./.vercel/project.json

          if [ $GITHUB_REF == 'refs/heads/master' ]; then
            _url=$( vercel  --prod --token "$TOKEN" )
          else
            _url=$( vercel --token "$TOKEN" )
          fi

          _url="${_url//'%'/'%25'}"
          _url="${_url//$'\n'/'%0A'}"
          _url="${_url//$'\r'/'%0D'}"
          echo "::set-output name=url::${_url}"
      - name: Create commit comment
        if: steps.vercel.conclusion == 'success'
        uses: daohoangson/comment-on-github@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: "Deployed ${{ github.sha }} to ${{ steps.vercel.outputs.url }}."
